import Navbar from "@/components/PageComponents/Navbar"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <title>OnlineStore</title>

      <body>
        <nav><Navbar /></nav>
        {children}
      </body>
    </html>
  )
}
